recipe: default.v1
language: de

pipeline:
  - name: SpacyNLP
    model: de_core_news_md
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: EntitySynonymMapper
  - name: DIETClassifier
    epochs: 200
