recipe: default.v1
language: en

pipeline:
  - name: SpacyNLP
    model: en_core_web_md
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: EntitySynonymMapper
  - name: DIETClassifier
    epochs: 200
