recipe: default.v1
language: en

pipeline:
 - name: "WhitespaceTokenizer"
    # Flag to check whether to split intents
   "intent_tokenization_flag": True
    # Symbol on which intent should be split
   "intent_split_symbol": "_"
    # Regular expression to detect tokens
   "token_pattern": None
 - name: LanguageModelFeaturizer
   model_name: "xlm"
   model_weights: "xlm-mlm-en-2048"
   cache_dir: null
   from_pt: True
 - name: CountVectorsFeaturizer
 - name: CountVectorsFeaturizer
   analyzer: "char_wb"
   min_ngram: 1
   max_ngram: 4
 - name: RegexFeaturizer
 - name: DIETClassifier
   epochs: 200
   batch_strategy: sequence
